name: app_estudos
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  shared_preferences: ^2.5.5
  vibration: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icones/

# Esta parte tem de ficar totalmente encostada à margem esquerda!
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icones/icone.png"
  adaptive_icon_background: "#0F0F0F"
  adaptive_icon_foreground: "assets/icones/icone.png"